### ISSUE TITLE
Get-content finding a wrong content value

### ISSUE THREAD

**Issue by carlosms-ms** [deividfoggi/M365-Distribution-Group-Migrator#4]
In the line 125, the content is writed in exo-password.sec but in the line 130 the get-content find for another value (exo-contoso.sec)
![Issue](https://user-images.githubusercontent.com/73181541/96599919-c9005980-12c6-11eb-89fa-681100d7ed76.png)
.

        $a.Password | ConvertFrom-SecureString | Set-Content exo-password.sec

        log -Status "CONN" -Message "User credentials for the user $a.UserName encripted"

        $userName = $a.UserName
        $password = Get-Content .\exo-contoso.sec | convertto-securestring

**Comment by deividfoggi** [comment]
Fixed in the following commit: https://github.com/deividfoggi/M365-Distribution-Group-Migrator/commit/ed428aff3d3230f724ece194d5b459fd3868af67

**Comment by carlosms-ms** [comment]
Great!!!!
Thank you ;)
